<?php

return array (
  'facebook_login' => 'Log in with Facebook',
  'linkedin_login' => 'Log in with Linkedin',
  'shibboleth_login' => 'Continue to Login',
  'email_address' => 'Email Address',
  'email' => 'Email',
  'password' => 'Password',
  'remember_me' => 'Remember me',
  'login' => 'Log in',
  'forgot_your_password' => 'Forgot Your Password?',
  'name' => 'Name',
  'confirm_password' => 'Confirm Password',
  'register' => 'Register',
  'have_an_account' => 'Already have an account?',
  'reset_password' => 'Reset Password',
  'new_password' => 'New Password',
  'send_reset_email' => 'Send Reset Email',
  'bio' => 'Business Name',
  'bio_placeholder' => 'e.g. Maiven Industries',
  'phone_number' => 'Phone Number',
  'phone_number_placeholder' => 'Your phone number',
  'avatar' => 'Your picture',
  'header_image' => 'Header Image',
  'update' => 'Update',
  'throttle' => 'Too many login attempts. Please try again in :seconds seconds.',
  'failed' => 'These credentials do not match our records.',
  'authenticate_with_a_provider' => 'Please authenticate with a provider below.',
);
