<?php

return array (
  'view_requirement' => 'View Requirement',
  'view_about_page' => 'View About Page',
  'view_idea_page' => 'Go to Topic Page',
  'reset_password' => 'Reset Password',
  'view_dashboard_page' => 'Visit Dashboard',
  'live_for_x' => ':idea_name will be live for :time.',
  'view_proposals_page' => 'View Plans',
  'direct_message_subject' => 'You have received a direct message from :user_name',
  'design_phase_open_subject' => 'Get Involved',
  'design_phase_updates_subject' => 'Get Involved - Updates',
  'support_subject' => 'Thanks for voting for :idea',
  'support_phase_updates_subject' => 'Vote - Updates',
  'contact_email_subject' => ':name has sent a message',
  'proposal_phase_updates_subject' => 'Attend - Updates',
  'quote_subject' => 'A little inspiration',
  'proposal_phase_open_subject' => 'Submit your plan',
  'welcome_subject' => 'Welcome to EventMovement',
  'invite_subject' => ':name wants you to vote for their topic suggestion',
  'comment_reply_subject' => ':user_name replied to your comment',
  'proposal_phase_failed_subject' => 'The Proposal phase is now complete',
  'update_posted_subject' => ':user_name has posted an update',
  'proposal_phase_complete_subject' => 'The Attend phase is complete',
  'support_phase_failed_subject' => 'Vote phase failed',
  'xmovement_requirement_invite_subject' => 'You have been nomintated by :name',
  'create_idea_subject' => 'You\'ve suggested a Topic',
);
