<?php

return array (
  'welcome_subject' => 'Welcome to EventMovement',
  'create_idea_subject' => 'You\'ve started an Idea',
  'update_posted_subject' => ':user_name has posted an update',
  'invite_subject' => ':name has sent you an invitation',
  'support_subject' => 'Thanks for supporting :idea',
  'design_phase_open_subject' => 'Start designing',
  'design_phase_updates_subject' => 'Design updates',
  'proposal_phase_complete_subject' => 'Offer phase is complete',
  'proposal_phase_open_subject' => 'Submit your Offer',
  'proposal_phase_updates_subject' => 'Offer updates',
  'support_phase_updates_subject' => 'Support updates',
  'xmovement_requirement_invite_subject' => 'You have been nomintated by :name',
  'direct_message_subject' => 'You have received a direct message from :user_name',
  'contact_email_subject' => ':name has sent a message',
  'proposal_phase_failed_subject' => 'Proposal phase is now complete',
  'comment_reply_subject' => ':user_name replied to your comment',
  'view_requirement' => 'View Requirement',
  'view_about_page' => 'View About Page',
  'reset_password' => 'Reset Password',
  'view_dashboard_page' => 'Visit Dashboard',
  'live_for_x' => ':idea_name will be live for :time.',
  'view_proposals_page' => 'View Plans',
  'view_idea_page' => 'Go to Idea Page',
);
