<?php

return array (
  'idea_updated' => 'Idea was updated',
  'idea_deleted' => 'Idea was deleted',
  'design_task_updated' => 'Design Task updated',
  'design_task_deleted' => 'Design Task deleted',
  'proposal_deleted' => 'Offer deleted',
  'proposal_updated' => 'Offer updated',
  'invites_sent_successfully' => 'Invites were sent successfully',
  'invites_not_sent' => 'Failed to send invites',
  'profile_updated' => 'Your profile was updated',
  'no_permission' => 'You do not have permission to do that',
  'design_phase_opened' => 'Design Phase is now open',
  'idea_not_found' => 'Idea not found',
  'user_not_found' => 'User not found',
  'page_not_found' => 'Page not found',
  'support_phase_closed' => 'The Support phase is closed',
  'design_phase_closed' => 'The Design phase is closed',
  'proposal_phase_closed' => 'The Offer phase is closed',
  'support_phase_locked' => 'The Support phase is locked',
  'design_phase_locked' => 'The Design phase is locked',
  'proposal_phase_locked' => 'The Offer phase is locked',
  'direct_message_sent' => 'Your message has been sent',
  'direct_message_sent_via_email' => 'Your message has been sent via email',
  'contact_message_sent' => 'Your message has been sent',
  'contact_message_failed' => 'Your message failed to send',
  'vote_twice_error' => 'You can\'t vote twice',
  'vote_up_twice_error' => 'You can\'t vote up twice',
  'vote_down_twice_error' => 'You can\'t vote down twice',
);
