<?php

return array (
  'page_not_found' => 'Page not found',
  'email_required' => 'Email required',
  'no_permission' => 'You do not have permission to do that',
  'user_not_found' => 'User not found',
  'profile_updated' => 'Your profile was updated',
  'vote_twice_error' => 'You can\'t vote twice',
  'content_reported' => 'Content reported',
  'something_went_wrong' => 'Something went wrong',
  'contact_message_sent' => 'Your message has been sent',
  'direct_message_sent' => 'Your message has been sent',
  'direct_message_sent_via_email' => 'Your message has been sent via email',
  'quote_sent_via_email' => 'Quote sent via email',
  'tender_phase_closed' => 'Tender Phase Closed',
  'tender_deleted' => 'Tender Deleted',
  'tender_created' => 'Tender Created',
  'inspiration_unfavourited' => 'Inspiration unfavourited',
  'inspiration_favourited' => 'Inspiration favourited',
  'inspiration_deleted' => 'Inspiration deleted',
  'post_not_found' => 'Post not found',
  'design_phase_closed' => 'Please sign in to contribute',
  'design_task_deleted' => 'Talking Point deleted',
  'proposal_phase_closed' => 'The Attend phase is closed',
  'proposal_deleted' => 'Plan deleted',
  'team_created' => 'Team Created',
  'idea_not_found' => 'Topic suggestion not found',
  'idea_updated' => 'Topic suggestion was updated',
  'idea_deleted' => 'Topic suggestion was deleted',
  'design_phase_opened' => 'The Get Involved phase is now open',
  'invites_not_sent' => 'Failed to send invites',
  'invites_sent_successfully' => 'Invites were sent successfully',
  'vote_up_twice_error' => 'You can\'t vote up twice',
  'vote_down_twice_error' => 'You can\'t vote down twice',
  'design_task_updated' => 'Talking Point updated',
  'proposal_updated' => 'Plan updated',
  'support_phase_closed' => 'The Vote phase is closed',
  'support_phase_locked' => 'The Vote phase is locked',
  'design_phase_locked' => 'The Get Invovled phase is locked',
  'proposal_phase_locked' => 'The Attend phase is locked',
);
