<?php

return array (
  'create_idea' => 'Start Idea',
  'edit_idea' => 'Edit Idea',
  'name_your_idea' => 'Start your Idea',
  'describe_your_idea' => 'A little more detail',
  'add_a_photo' => 'Express your Idea with an image',
  'settings' => 'Set your Idea duration',
  'timeframes' => 'Timeframes',
  'name_label' => 'Choose a name for your idea. Short and self-explanatory works best. (Don\'t worry, you can change this later)',
  'description_label' => 'Add a short description of your Idea to help people understand it better. For example, what is the Idea about? Why do you think it is a good Idea? (You can always edit this later)',
  'photo_label' => 'Express your Idea with an image',
  'visibility_label' => 'Do you want this Idea to be public? (Public Ideas are visible on the Explore page)',
  'proposals_during_design_label' => 'Start the Plan It phase at the same time as the Get Involved phase',
  'design_during_support_label' => 'Start the Get Involved phase straight away',
  'supporters_target_label' => 'Target number of supporters',
  'duration_label' => 'Each idea goes through the Support, Get Involved and Plan It phases before it is complete. Pick a duration for your idea in days.',
  'name_placeholder' => 'E.g. Study Skills Training...',
  'supporters_target_placeholder' => '0',
  'next_step' => 'Next Step',
  'previous_step' => 'Previous Step',
  'save_changes' => 'Save Changes',
  'description_placeholder' => 'Describe your Idea',
  'questions' => 'Ask Some Questions',
  'questions_label' => 'What questions would you like to ask your supporters in the design phase to help shape your event?',
  'question_1_placeholder' => 'An example question',
  'question_2_placeholder' => 'An example question',
  'question_3_placeholder' => 'An example question',
  'category_label' => 'Category',
);
