<?php

return array (
  'name_your_idea' => 'Suggest a Topic',
  'edit_idea' => 'Edit Topic',
  'create_idea' => 'Suggest Topic',
  'questions' => 'Ask Some Questions',
  'questions_label' => 'What questions would you like to ask in the Discuss Phase to help shape your topic?',
  'question_1_placeholder' => 'An example question',
  'question_2_placeholder' => 'An example question',
  'question_3_placeholder' => 'An example question',
  'next_step' => 'Next Step',
  'previous_step' => 'Previous Step',
  'settings' => 'Set your Topic duration',
  'visibility_label' => 'Do you want this Topic suggestion to be public? (Public suggestions are visible on the Explore page)',
  'duration_label' => 'Each Topic suggestion goes through the Vote,Discuss and Attend phases before it is complete. Pick a duration for your Topic in days.',
  'save_changes' => 'Save Changes',
  'name_label' => 'What is the title of your topic? Short and self-explanatory works best. (Don\'t worry, you can change this later)',
  'name_placeholder' => 'E.g. Virtual Reality / Artificial Intelligence',
  'category_label' => 'Select a category',
  'add_a_photo' => 'Express your Topic with an image',
  'describe_your_idea' => 'A little more detail',
  'description_label' => 'Add a short description of the Topic to help people understand it better. For example, what is the Topic about? Why do you think it is an interesting topic? (You can always edit this later)',
  'description_placeholder' => 'Describe your Topic',
  'timeframes' => 'Timeframes',
  'photo_label' => 'Express your Topic with an image',
  'proposals_during_design_label' => 'Start the Attend phase at the same time as the Discuss phase',
  'design_during_support_label' => 'Start the Discuss phase straight away',
  'supporters_target_label' => 'Target number of votes',
  'supporters_target_placeholder' => '0',
);
