<?php

return array (
  'default_title' => 'Create by CityLit',
  'home_title' => 'Home - Create by CityLit',
  'home_description' => 'Welcome to Create by CityLit',
  'about_title' => 'About - Create by CityLit',
  'about_description' => 'About Create by CityLit',
  'contact_title' => 'Contact - Create by CityLit',
  'contact_description' => 'Contact Create by CityLit',
  'terms_title' => 'Terms - Create by CityLit',
  'terms_description' => 'The Terms & Conditions of EventMovement',
  'ideas_index_title' => 'Ideas - Create by CityLit',
  'ideas_index_description' => 'Discover Ideas',
  'ideas_view_title' => ':idea_name - Create by CityLit',
  'ideas_view_description' => 'Support :user_name\'s idea \':idea_name\' on Create by CityLit',
  'profile_description' => 'A user profile',
  'user_details_title' => 'User Details',
  'user_details_description' => 'Please add some user details',
  'admin_title' => 'Admin',
  'admin_description' => 'The admin area',
  'blog_index_title' => 'Blog',
  'blog_index_description' => 'Welcome to the blog',
  'blog_post_view_title' => 'Blog Post',
  'blog_post_description' => 'A blog post',
  'translation_title' => 'Translation',
  'translation_description' => 'Translate tool',
  'analytics_title' => 'Analytics',
  'analytics_description' => 'Site analytics',
  'default_description' => 'A page',
);
