<?php

return array (
  'default_title' => 'EventMovement - An ideation platform',
  'home_title' => 'Home - EventMovement',
  'home_description' => 'Welcome to EventMovement',
  'about_title' => 'About - EventMovement',
  'about_description' => 'About EventMovement',
  'contact_title' => 'Contact - EventMovement',
  'contact_description' => 'Contact EventMovement',
  'terms_title' => 'Terms - EventMovement',
  'terms_description' => 'The Terms & Conditions of EventMovement',
  'ideas_index_title' => 'Ideas - EventMovement',
  'ideas_index_description' => 'Discover Ideas',
  'ideas_view_title' => ':idea_name - EventMovement',
  'ideas_view_description' => 'Support :user_name\'s idea \':idea_name\' on EventMovement',
  'analytics_title' => 'Analytics - EventMovement',
  'analytics_description' => 'View analytics for the EventMovement platform',
  'translation_title' => 'Translation - EventMovement',
  'translation_description' => 'Translate files on the EventMovement platform',
  'competition_title' => 'Competition - EventMovement',
  'competition_description' => 'Details about the EventMovement competition',
  'admin_title' => 'Admin',
  'admin_description' => 'Tools for managing the platform.',
  'blog_index_title' => 'Blog',
  'blog_index_description' => 'Event Movement blog page',
  'blog_post_view_title' => 'Blog Post',
  'blog_post_description' => 'A blog post',
  'profile_description' => 'A user profile',
  'user_details_title' => 'User Details',
  'user_details_description' => 'Please add some user details',
  'default_description' => 'A page',
);
