<?php

return array (
  'add_to_proposal' => 'Add to plan',
  'remove_from_proposal' => 'Remove from plan',
  'winner' => 'WINNER',
  'added_x_ago' => 'Added :time',
  'posted_by_x' => 'Posted by :name',
  'view_proposal' => 'View plan',
  'proposals' => 'Plans',
  'add_proposal' => 'Make a new plan',
  'review_proposal' => 'Review plan',
  'review_proposal_subtitle' => 'Finalise your plan by reordering elements and adding comments',
  'cancel' => 'Cancel',
  'submit_confirmation' => 'Are you sure you want to submit this plan?',
  'description' => 'Description',
  'description_placeholder' => 'Describe your plan...',
  'upload_document' => 'Upload a document',
  'submit_proposal' => 'Submit plan',
  'previous' => 'Previous',
  'next' => 'Next',
  'proposal' => 'Plan',
  'back_to_proposals' => 'Back to plans',
  'delete_proposal' => 'Delete plan',
  'added_by_x_x' => 'Added by :name :time',
  'view_proopsal_document' => 'View proposal document',
  'your_proposal' => 'Your plan',
  'save_for_later' => 'Save for later',
  'get_started' => 'Get Started',
  'maybe_later' => 'Maybe later',
  'step_one' => 'Select the talking points you would like to include in your plan',
  'step_two' => 'You will then be asked to choose one or more contributions from each. Pick the ones that work best and are popular choices',
  'step_three' => 'Finally, review your plan and add comments to explain the decisions you\'ve made and why you think your plan works',
  'select_design_tasks' => 'Select Talking Points',
  'select_design_tasks_subtitle' => 'Select the talking points you would like to include in your plan',
);
