<?php

return array (
  'proposal' => 'Proposal',
  'proposals' => 'Proposals',
  'back_to_proposals' => 'Back to proposals',
  'your_proposal' => 'Your proposal',
  'add_proposal' => 'Make a new proposal',
  'delete_proposal' => 'Delete proposal',
  'view_proposal' => 'View proposal',
  'submit_proposal' => 'Submit proposal',
  'save_for_later' => 'Save for later',
  'get_started' => 'Get Started',
  'maybe_later' => 'Maybe later',
  'added_x_ago' => 'Added :time',
  'added_by_x_x' => 'Added by :name :time',
  'posted_by_x' => 'Posted by :name',
  'winner' => 'WINNER',
  'step_one' => 'Select the talking points you would like to include in your proposal',
  'step_two' => 'You will then be asked to choose one or more contributions from each. Pick the ones that work best and are popular choices',
  'step_three' => 'Finally, review your proposal and add comments to explain the decisions you\'ve made and why you think your proposal works',
  'previous' => 'Previous',
  'next' => 'Next',
  'cancel' => 'Cancel',
  'select_design_tasks' => 'Select Talking Points',
  'select_design_tasks_subtitle' => 'Select the talking points you would like to include in your proposal',
  'add_to_proposal' => 'Add to proposal',
  'remove_from_proposal' => 'Remove from proposal',
  'review_proposal' => 'Review propsoal',
  'review_proposal_subtitle' => 'Finalise your proposal by reordering elements and adding comments',
  'description' => 'Description',
  'description_placeholder' => 'Describe your proposal...',
  'submit_confirmation' => 'Are you sure you want to submit this proposal?',
);
